### ISSUE TITLE
Clarification on potential inaccuracy described in README

### ISSUE THREAD

**Issue by veilm** [robpike/kata#2]
The REAMDE says ``Note that the output may not be accurate because of false matches and the inability to generate things like the tsu consonant-extending symbol.``

What are false matches in this context?
What do you mean by inability to generate tsu? I can see that ``kata beddo`` successfully produces べッド, for example.

**Comment by robpike** [comment]
I wrote this a long time ago and don't remember an exact example, but the matching algorithm can make mistakes because correct transliteration has some context-dependent characteristics.
